version: "3.4"
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: db
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - "db"
    ports:
      - "8080:8080"
